/**
 * RC-DSN-2.1 — the design system's built-in English copy.
 *
 * These strings were JSX literals while the design system was `.jsx` and outside the
 * `i18n/no-literal-jsx-text` rule. The TSX conversion keeps them byte-for-byte (no behaviour
 * change) and reads them from here. They are not localized yet: DS primitives render outside
 * `useI18n` in tests and galleries, so routing them through the app catalogs (and adding Spanish)
 * is its own story, tracked with DEBT-2026-002 in `DEBT.md`.
 */
export const dsCopy = {
	'ds.questCard.reward': 'Reward',
	'ds.commandPalette.commandPalette': 'Command palette',
	'ds.commandPalette.results': 'Results',
	'ds.commandPalette.navigate': ' navigate',
	'ds.commandPalette.select': ' select',
	'ds.commandPalette.close': ' close',
	'ds.conditionTracker.noConditions': 'No conditions',
	'ds.conditionTracker.thisSystemHasNoConditions': 'This system has no conditions.',
	'ds.conditionTracker.addCondition': 'Add condition',
	'ds.conditionTracker.condition': ' Condition',
	'ds.brand.lamp': 'Lamp',
	'ds.brand.light': 'light',
	'ds.brand.lamplight': 'Lamplight',
	'ds.breadcrumb.areaUnavailable': 'Area unavailable',
	'ds.breadcrumb.unavailable': ' Unavailable',
	'ds.popover.close': 'Close',
	'ds.tabs.sections': 'Sections',
	'ds.statBlock.cr': 'CR',
	'ds.statBlock.armorClass': 'Armor Class',
	'ds.statBlock.hitPoints': 'Hit Points',
	'ds.statBlock.speed': 'Speed',
	'ds.statBlock.thisCombatant': 'This combatant',
	'ds.statBlock.savingThrows': 'Saving Throws',
	'ds.statBlock.skills': 'Skills',
	'ds.statBlock.damageResistances': 'Damage Resistances',
	'ds.statBlock.damageImmunities': 'Damage Immunities',
	'ds.statBlock.conditionImmunities': 'Condition Immunities',
	'ds.statBlock.senses': 'Senses',
	'ds.statBlock.languages': 'Languages',
	'ds.statBlock.challenge': 'Challenge',
	'ds.statBlock.xp': ' XP)',
	'ds.statBlock.proficiencyBonus': 'Proficiency Bonus',
	'ds.statBlock.actions': 'Actions',
	'ds.statBlock.bonusActions': 'Bonus Actions',
	'ds.statBlock.reactions': 'Reactions',
	'ds.statBlock.legendaryActions': 'Legendary Actions',
	'ds.chip.remove': 'Remove',
	'ds.fogControls.fogOfWar': ' Fog of war',
	'ds.fogControls.reveal': ' Reveal',
	'ds.fogControls.conceal': ' Conceal',
	'ds.fogControls.brushSize': 'Brush size',
	'ds.fogControls.fogBrushSize': 'Fog brush size',
	'ds.fogControls.featherEdge': 'Feather edge',
	'ds.fogControls.revealAll': ' Reveal all',
	'ds.fogControls.resetFog': ' Reset fog',
	'ds.generationPanel.generateMapLayers': 'Generate map layers',
	'ds.generationPanel.seed': 'Seed',
	'ds.generationPanel.eGCrypt1': 'e.g. crypt-1',
	'ds.generationPanel.randomizeSeed': 'Randomize seed',
	'ds.generationPanel.size': 'Size',
	'ds.generationPanel.waterCoverage': 'Water coverage',
	'ds.generationPanel.elevationProfile': 'Elevation profile',
	'ds.generationPanel.trapHazardDensity': 'Trap & hazard density',
	'ds.generationPanel.advancedSettings': ' Advanced settings',
	'ds.generationPanel.riverDensity': 'River density',
	'ds.generationPanel.roadDensity': 'Road density',
	'ds.generationPanel.biomeCount': 'Biome count',
	'ds.generationPanel.preview': 'preview · ',
	'ds.generationPanel.generating': 'Generating…',
	'ds.generationPanel.generationProgress': 'Generation progress',
	'ds.generationPanel.acceptAmpAdd': 'Accept & add',
	'ds.generationPanel.discard': 'Discard',
	'ds.importWizard.importMap': 'Import map',
	'ds.importWizard.silverdaleRegionPng': 'silverdale-region.png',
	'ds.importWizard.42Mb': ' · 4.2 MB',
	'ds.importWizard.pngJpgSvgUpTo50Mb': 'PNG, JPG, SVG · up to 50 MB',
	'ds.importWizard.adapterFormat': 'Adapter / format',
	'ds.importWizard.eGFoundryScene': 'e.g. foundry-scene',
	'ds.importWizard.cancel': 'Cancel',
	'ds.importWizard.preview': 'Preview',
	'ds.importWizard.unsupportedFormatNoAdapterDeclaredThereIsNoCommit':
		'Unsupported format — no adapter declared. There is no commit path for this file.',
	'ds.importWizard.theseElementsWillNotBeImported': 'These elements will not be imported: ',
	'ds.importWizard.back': 'Back',
	'ds.importWizard.cancelRollback': 'Cancel (rollback)',
	'ds.importWizard.commitImport': 'Commit import',
	'ds.importWizard.silverdaleRegionImported': 'Silverdale Region imported',
	'ds.importWizard.5LayersCreatedBaseImageWallsGridLightsRegions':
		'5 layers created · base image, walls, grid, lights, regions',
	'ds.importWizard.close': 'Close',
	'ds.importWizard.openMap': 'Open map',
	'ds.layerPanel.clear': 'Clear',
	'ds.layerPanel.addLayer': ' Add layer',
	'ds.layerRow.opacity': 'Opacity',
	'ds.mapCreationForm.createANewMap': 'Create a new map',
	'ds.mapCreationForm.name': 'Name',
	'ds.mapCreationForm.eGSunlessCitadel': 'e.g. Sunless Citadel',
	'ds.mapCreationForm.scale': 'Scale',
	'ds.mapCreationForm.unitsPerMap': 'Units per map',
	'ds.mapCreationForm.miles': 'miles',
	'ds.mapCreationForm.unitLabel': 'Unit label',
	'ds.mapCreationForm.projection': 'Projection',
	'ds.mapCreationForm.defaultVisibility': 'Default visibility',
	'ds.mapCreationForm.newMapsDefaultTo': 'New maps default to',
	'ds.mapCreationForm.dmOnly': 'DM only',
	'ds.mapCreationForm.safeToShareWhenReady': ' — safe to share when ready.',
	'ds.mapCreationForm.cancel': 'Cancel',
	'ds.minimap.expandMinimap': 'Expand minimap',
	'ds.minimap.minimapCurrentViewportHighlighted': 'Minimap — current viewport highlighted',
	'ds.minimap.minimap': 'Minimap',
	'ds.minimap.collapseMinimap': 'Collapse minimap',
	'ds.minimap.jumpViewportClickASpotOrUseTheArrow':
		'Jump viewport — click a spot, or use the arrow keys to pan',
	'ds.pOIPopover.focusOnMap': 'Focus on map',
	'ds.pOIPopover.edit': 'Edit',
	'ds.pOIPopover.copyLink': 'Copy link',
	'ds.pOIPopover.delete': 'Delete',
	'ds.pOIPopover.linkedNote': 'Linked note',
	'ds.pOIPopover.readNote': 'Read note',
	'ds.pOIPopover.visibility': 'Visibility',
	'ds.pOIPopover.independentOfTheLayerADmOnlyPoiNever':
		'Independent of the layer — a DM-only POI never appears in player lists or search.',
	'ds.toolPalette.drawingTools': 'Drawing tools',
	'ds.toolPalette.moreTools': 'More tools',
	'ds.toolPalette.undoLastStroke': 'Undo last stroke',
	'ds.toolPalette.undoZ': 'Undo (⌘Z)',
	'ds.toolPalette.redo': 'Redo',
	'ds.toolPalette.redoZ': 'Redo (⌘⇧Z)',
	'ds.bottomTabBar.primary': 'Primary',
	'ds.navRail.primary': 'Primary',
	'ds.navSidebar.primary': 'Primary',
	'ds.dialog.close': 'Close',
	'ds.sheet.close': 'Close',
	'ds.toast.dismiss': 'Dismiss',
	'ds.spellCard.concentration': 'Concentration',
	'ds.spellCard.ritual': 'Ritual',
	'ds.spellCard.castingTime': 'Casting time',
	'ds.spellCard.range': 'Range',
	'ds.spellCard.components': 'Components',
	'ds.spellCard.duration': 'Duration',
	'ds.spellCard.atHigherLevels': 'At higher levels. ',
} as const;
