/**
 * RC-UX-1.4 — COMMUNITY TRANSLATION WORKFLOW. Round-trips the app's message catalogs
 * (`apps/gm-react/src/i18n/messages/*.ts`) through the flat monolingual-JSON shape Weblate and
 * Crowdin both ingest for a "JSON file" component, so a community translator never touches
 * TypeScript.
 *
 * `export` writes one JSON per locale under `i18n-export/`: `en.json` is the source (every key,
 * en value, for translator context) and `<locale>.json` holds only the keys that locale has
 * already translated. `import` reads a translated `<locale>.json` back and regenerates
 * `messages/<locale>.ts` — keys not present in the upload are dropped (a translator who deletes a
 * row on the platform is deleting the translation, not silently keeping the stale one), keys the
 * upload has that `en.ts` no longer declares are rejected (a removed key never leaks back in), and
 * the emitted file keeps `en.ts`'s key ORDER so the diff for a routine sync stays reviewable.
 *
 * Usage:
 *   tsx scripts/i18n-catalog.ts export [--dir i18n-export] [--locale es]
 *   tsx scripts/i18n-catalog.ts import --locale es [--dir i18n-export]
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import process from 'node:process';
import { en, type MessageKey } from '../apps/gm-react/src/i18n/messages/en';
import { SUPPORTED_LOCALES, type SupportedLocale } from '../apps/gm-react/src/i18n';

const HERE = fileURLToPath(new URL('.', import.meta.url));
const REPO_ROOT = resolve(HERE, '..');
const MESSAGES_DIR = join(REPO_ROOT, 'apps/gm-react/src/i18n/messages');

const TRANSLATABLE_LOCALES: readonly SupportedLocale[] = SUPPORTED_LOCALES.map(
	(locale) => locale.code,
).filter((code): code is SupportedLocale => code !== 'en');

export type FlatCatalog = Record<string, string>;

/** Loads a locale's catalog module. `en` is already in this process; every other locale is a
 * plain object literal, so a dynamic import resolves it without a build step. */
async function loadLocaleCatalog(
	locale: SupportedLocale,
): Promise<Partial<Record<MessageKey, string>>> {
	if (locale === 'en') return en;
	const path = join(MESSAGES_DIR, `${locale}.ts`);
	if (!existsSync(path)) return {};
	const module = (await import(pathToFileURL(path).href)) as Record<
		string,
		Partial<Record<MessageKey, string>>
	>;
	return module[locale] ?? {};
}

export function exportSourceCatalog(): FlatCatalog {
	return { ...en };
}

export function exportLocaleCatalog(catalog: Partial<Record<MessageKey, string>>): FlatCatalog {
	const flat: FlatCatalog = {};
	for (const key of Object.keys(en) as MessageKey[]) {
		const value = catalog[key];
		if (value !== undefined) flat[key] = value;
	}
	return flat;
}

/** The `messages/<locale>.ts` TEXT for an uploaded catalog. Validates every key against `en`'s
 * key space first — `MessageKey` is a compile-time union, so an unknown key would otherwise only
 * surface as a `pnpm typecheck` failure far from the translation upload that caused it. */
export function buildLocaleModule(locale: SupportedLocale, uploaded: FlatCatalog): string {
	const knownKeys = new Set(Object.keys(en));
	const unknown = Object.keys(uploaded).filter((key) => !knownKeys.has(key));
	if (unknown.length > 0) {
		throw new Error(
			`${locale}.json has ${unknown.length} key(s) en.ts no longer declares: ${unknown.slice(0, 5).join(', ')}${unknown.length > 5 ? ', …' : ''}`,
		);
	}
	const entries = (Object.keys(en) as MessageKey[])
		.filter((key) => uploaded[key] !== undefined)
		.map((key) => `\t${JSON.stringify(key)}: ${JSON.stringify(uploaded[key])},`)
		.join('\n');
	return (
		`import type { MessageKey } from './en';\n\n` +
		`/** Generated by \`tsx scripts/i18n-catalog.ts import --locale ${locale}\` from the community\n` +
		` * translation platform export — do not hand-edit; re-run the import instead\n` +
		` * (docs/development/LOCALIZATION.md). A \`Partial\` of \`en\`: an untranslated key renders its\n` +
		` * English source rather than a blank or a bare identifier, so a partly translated locale\n` +
		` * degrades honestly. */\n` +
		`export const ${locale}: Partial<Record<MessageKey, string>> = {\n${entries}\n};\n`
	);
}

function readJson(path: string): FlatCatalog {
	return JSON.parse(readFileSync(path, 'utf8')) as FlatCatalog;
}

async function runExport(dir: string, locales: readonly SupportedLocale[]): Promise<void> {
	mkdirSync(dir, { recursive: true });
	writeFileSync(join(dir, 'en.json'), `${JSON.stringify(exportSourceCatalog(), null, '\t')}\n`);
	console.log(`wrote ${join(dir, 'en.json')} (${Object.keys(en).length} keys)`);
	for (const locale of locales) {
		const catalog = await loadLocaleCatalog(locale);
		const flat = exportLocaleCatalog(catalog);
		const path = join(dir, `${locale}.json`);
		writeFileSync(path, `${JSON.stringify(flat, null, '\t')}\n`);
		console.log(`wrote ${path} (${Object.keys(flat).length}/${Object.keys(en).length} keys)`);
	}
}

async function runImport(dir: string, locale: SupportedLocale): Promise<void> {
	const path = join(dir, `${locale}.json`);
	if (!existsSync(path)) throw new Error(`no export found at ${path} — run \`export\` first`);
	const uploaded = readJson(path);
	const outPath = join(MESSAGES_DIR, `${locale}.ts`);
	writeFileSync(outPath, buildLocaleModule(locale, uploaded));
	console.log(`wrote ${outPath} (${Object.keys(uploaded).length} keys)`);
}

function parseArgs(argv: readonly string[]): {
	command: 'export' | 'import';
	dir: string;
	locale?: SupportedLocale;
} {
	const [command, ...rest] = argv;
	if (command !== 'export' && command !== 'import') {
		throw new Error(
			'usage: tsx scripts/i18n-catalog.ts <export|import> [--dir <path>] [--locale <code>]',
		);
	}
	let dir = join(REPO_ROOT, 'i18n-export');
	let locale: SupportedLocale | undefined;
	for (let i = 0; i < rest.length; i += 1) {
		if (rest[i] === '--dir') dir = resolve(REPO_ROOT, rest[(i += 1)]);
		else if (rest[i] === '--locale') locale = rest[(i += 1)] as SupportedLocale;
	}
	return { command, dir, locale };
}

async function main(): Promise<void> {
	const { command, dir, locale } = parseArgs(process.argv.slice(2));
	if (command === 'export') {
		await runExport(dir, locale ? [locale] : TRANSLATABLE_LOCALES);
		return;
	}
	if (!locale) throw new Error('import requires --locale <code>');
	if (!TRANSLATABLE_LOCALES.includes(locale)) {
		throw new Error(`unsupported locale "${locale}" — add it to SUPPORTED_LOCALES first`);
	}
	await runImport(dir, locale);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
	main().catch((error: unknown) => {
		console.error(error instanceof Error ? error.message : error);
		process.exitCode = 1;
	});
}
