/**
 * RC-UX-1.2 ratchet for `no-literal-jsx-text`.
 *
 * Each entry is a file that still renders untranslated user-visible text, and the number of
 * strings it is allowed to keep. The rule fails when a file exceeds its number *and* when it
 * comes in under it — a migrated screen has to lower or delete its entry in the same commit, so
 * this list can only ever get shorter.
 *
 * Adding a file here is not a way to land new untranslated copy. New screens carry no entry, so
 * the first literal they render fails the gate.
 */
export const allow = {
	'apps/gm-react/src/app/ConnectedSources.tsx': 31,
	'apps/gm-react/src/app/EncounterBuilder.tsx': 21,
	'apps/gm-react/src/app/SceneBoardCanvas.tsx': 3,
	'apps/gm-react/src/app/charBuilder/Choose.tsx': 6,
	'apps/gm-react/src/app/charBuilder/Import.tsx': 9,
	'apps/gm-react/src/app/charBuilder/Overlay.tsx': 7,
	'apps/gm-react/src/app/charBuilder/Review.tsx': 3,
	'apps/gm-react/src/app/charBuilder/index.tsx': 5,
	'apps/gm-react/src/app/charBuilder/steps/Abilities.tsx': 8,
	'apps/gm-react/src/app/charBuilder/steps/Bio.tsx': 11,
	'apps/gm-react/src/app/charBuilder/steps/ClassLevel.tsx': 7,
	'apps/gm-react/src/app/charBuilder/steps/Identity.tsx': 12,
	'apps/gm-react/src/app/charBuilder/steps/Kit.tsx': 19,
	'apps/gm-react/src/app/map/ImportMapDialog.tsx': 20,
	'apps/gm-react/src/app/map/MapEditor.tsx': 22,
	'apps/gm-react/src/app/map/QuickMapRail.tsx': 4,
	'apps/gm-react/src/app/map/StatusBar.tsx': 2,
	'apps/gm-react/src/app/map/ToolOptionsBar.tsx': 22,
	'apps/gm-react/src/app/map/ToolRail.tsx': 1,
	'apps/gm-react/src/app/map/canvas/EditorCanvas.tsx': 4,
	'apps/gm-react/src/app/map/canvas/MapCanvas.tsx': 1,
	'apps/gm-react/src/app/map/dock/AssetsPanel.tsx': 7,
	'apps/gm-react/src/app/map/dock/HistoryPanel.tsx': 7,
	'apps/gm-react/src/app/map/dock/InspectorPanel.tsx': 48,
	'apps/gm-react/src/app/map/dock/LayersPanel.tsx': 20,
	'apps/gm-react/src/app/map/generate/GeneratePanel.tsx': 19,
	'apps/gm-react/src/app/widget-bodies.tsx': 15,
	'apps/gm-react/src/app/widgets/templates/ActionPanel.tsx': 1,
	'apps/gm-react/src/app/widgets/templates/FormPanel.tsx': 2,
	'apps/gm-react/src/app/widgets/templates/SceneMessage.tsx': 1,
	'apps/gm-react/src/app/widgets/templates/StatBlock.tsx': 1,
	'apps/gm-react/src/app/widgets/templates/StatusList.tsx': 1,
	'apps/gm-react/src/screens/Board.tsx': 19,
	'apps/gm-react/src/screens/Campaign.tsx': 37,
	'apps/gm-react/src/screens/CommandCenter.tsx': 10,
	'apps/gm-react/src/screens/Graph.tsx': 18,
	'apps/gm-react/src/screens/Join.tsx': 15,
	'apps/gm-react/src/screens/SceneCardsPanel.tsx': 4,
	'apps/gm-react/src/screens/SceneDisplay.tsx': 2,
	'apps/gm-react/src/screens/ScenesCreator.tsx': 18,
	'apps/gm-react/src/screens/Upgrade.tsx': 25,
	'apps/gm-react/src/screens/WikiReader.tsx': 17,
	'apps/gm-react/src/screens/atlas/AtlasCanvas.tsx': 6,
	'apps/gm-react/src/screens/atlas/FogPanel.tsx': 4,
	'apps/gm-react/src/screens/atlas/LayersPanel.tsx': 6,
	'apps/gm-react/src/screens/atlas/MapChips.tsx': 2,
	'apps/gm-react/src/screens/atlas/NoticeBar.tsx': 2,
	'apps/gm-react/src/screens/atlas/PoiPanel.tsx': 6,
	'apps/gm-react/src/screens/audio/AutomationTab.tsx': 18,
	'apps/gm-react/src/screens/audio/NowPlaying.tsx': 5,
	'apps/gm-react/src/screens/audio/PresetsTab.tsx': 11,
	'apps/gm-react/src/screens/audio/index.tsx': 1,
	'apps/gm-react/src/screens/audio/panels/PlaybackLeft.tsx': 12,
	'apps/gm-react/src/screens/audio/panels/PlaybackRight.tsx': 15,
	'apps/gm-react/src/screens/characters/CharCard.tsx': 1,
	'apps/gm-react/src/screens/characters/CharacterSheet.tsx': 1,
	'apps/gm-react/src/screens/characters/index.tsx': 6,
	'apps/gm-react/src/screens/characters/shared.tsx': 2,
	'apps/gm-react/src/screens/characters/sheet/AbilitiesPanel.tsx': 9,
	'apps/gm-react/src/screens/characters/sheet/AdvancementPanel.tsx': 18,
	'apps/gm-react/src/screens/characters/sheet/AttacksPanel.tsx': 12,
	'apps/gm-react/src/screens/characters/sheet/BioPanel.tsx': 2,
	'apps/gm-react/src/screens/characters/sheet/CombatPanel.tsx': 14,
	'apps/gm-react/src/screens/characters/sheet/ReferencePanel.tsx': 1,
	'apps/gm-react/src/screens/characters/sheet/SharingPanel.tsx': 6,
	'apps/gm-react/src/screens/characters/sheet/SheetHeader.tsx': 3,
	'apps/gm-react/src/screens/characters/sheet/SpellsPanel.tsx': 10,
	'apps/gm-react/src/screens/sceneEditor/AddWidgetPanel.tsx': 3,
	'apps/gm-react/src/screens/sceneEditor/Inspector.tsx': 13,
	'apps/gm-react/src/screens/sceneEditor/SceneMetaPanel.tsx': 7,
	'apps/gm-react/src/screens/sceneEditor/index.tsx': 8,
};
