import React from 'react';
import {
	DoorOpen,
	Lightbulb,
	PenTool,
	RectangleHorizontal,
	SprayCan,
	Trees,
	Accessibility,
	Activity,
	Anchor,
	ArrowBigUpDash,
	ArrowDownToLine,
	ArrowLeft,
	ArrowRight,
	ArrowUp,
	Ban,
	Banana,
	Bandage,
	BatteryLow,
	Bed,
	Blend,
	BookOpen,
	Brain,
	BrickWall,
	BriefcaseBusiness,
	Brush,
	CalendarDays,
	ChartNoAxesColumn,
	ChartPie,
	Check,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Circle,
	CircleCheck,
	CircleDashed,
	CircleDot,
	CircleX,
	Clapperboard,
	ClipboardCheck,
	Clock,
	Cloud,
	CloudFog,
	CloudLightning,
	CloudSun,
	CloudUpload,
	Clover,
	Coffee,
	Coins,
	Columns3,
	Cone,
	Contrast,
	Copy,
	CreditCard,
	Crosshair,
	DatabaseZap,
	Diamond,
	DiamondMinus,
	DiamondPercent,
	Dice6,
	Dices,
	Download,
	Droplet,
	Droplets,
	Dumbbell,
	EarOff,
	Ellipsis,
	Eraser,
	Eye,
	EyeClosed,
	EyeOff,
	Feather,
	Flag,
	Flame,
	FlameKindling,
	Flashlight,
	FlaskConical,
	Focus,
	FolderOpen,
	Footprints,
	Gauge,
	Gem,
	Ghost,
	Globe,
	Grab,
	GraduationCap,
	Grid3x3,
	GripVertical,
	Group,
	Hand,
	Haze,
	Heart,
	HeartCrack,
	HeartHandshake,
	Hexagon,
	Hourglass,
	House,
	Import,
	Infinity,
	Info,
	Landmark,
	Languages,
	Lasso,
	Layers,
	LayoutDashboard,
	LayoutGrid,
	Library,
	Link2,
	ListOrdered,
	LoaderCircle,
	LocateOff,
	Lock,
	LockOpen,
	LogIn,
	LogOut,
	Magnet,
	Map,
	MapPin,
	MapPinPlus,
	Maximize,
	Meh,
	Milestone,
	Minus,
	Monitor,
	Moon,
	Mountain,
	MousePointer2,
	Move,
	NotebookPen,
	PaintBucket,
	Palette,
	Pause,
	PawPrint,
	Pencil,
	PencilLine,
	Pentagon,
	PictureInPicture2,
	Pin,
	Play,
	Plug,
	Plus,
	Popcorn,
	Rabbit,
	Redo2,
	RotateCcw,
	Route,
	Ruler,
	Scroll,
	Search,
	Send,
	Settings,
	Shapes,
	Share2,
	Shield,
	ShieldCheck,
	ShieldOff,
	Shrub,
	Shuffle,
	Sigma,
	SkipForward,
	Skull,
	SlidersHorizontal,
	Snail,
	Sparkles,
	Spline,
	Sprout,
	Square,
	Stamp,
	Stars,
	Sun,
	SunDim,
	SunMoon,
	Sunrise,
	Swords,
	Tag,
	Tally3,
	Target,
	Thermometer,
	Timer,
	Tornado,
	Trash2,
	TrendingUp,
	Triangle,
	TriangleAlert,
	Type,
	Undo2,
	UserCircle,
	UserPlus,
	Users,
	UsersRound,
	VenetianMask,
	Volume2,
	VolumeX,
	Wand,
	WandSparkles,
	Waves,
	Waypoints,
	Weight,
	Wind,
	Wrench,
	X,
	Zap,
	ZapOff,
	ZoomIn,
	ZoomOut,
} from 'lucide-react';

// Keep the glyph allowlist explicit. Importing Lucide's dynamic `icons` record retained every icon
// in the entry chunk (roughly 0.8 MB before minification), even though the app uses this small,
// release-reviewed vocabulary.
const GLYPHS = Object.freeze({
	DoorOpen,
	Lightbulb,
	PenTool,
	RectangleHorizontal,
	SprayCan,
	Trees,
	Accessibility,
	Activity,
	Anchor,
	ArrowBigUpDash,
	ArrowDownToLine,
	ArrowLeft,
	ArrowRight,
	ArrowUp,
	Ban,
	Banana,
	Bandage,
	BatteryLow,
	Bed,
	Blend,
	BookOpen,
	Brain,
	BrickWall,
	BriefcaseBusiness,
	Brush,
	CalendarDays,
	ChartNoAxesColumn,
	ChartPie,
	Check,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Circle,
	CircleCheck,
	CircleDashed,
	CircleDot,
	CircleX,
	Clapperboard,
	ClipboardCheck,
	Clock,
	Cloud,
	CloudFog,
	CloudLightning,
	CloudSun,
	CloudUpload,
	Clover,
	Coffee,
	Coins,
	Columns3,
	Cone,
	Contrast,
	Copy,
	CreditCard,
	Crosshair,
	DatabaseZap,
	Diamond,
	DiamondMinus,
	DiamondPercent,
	Dice6,
	Dices,
	Download,
	Droplet,
	Droplets,
	Dumbbell,
	EarOff,
	Ellipsis,
	Eraser,
	Eye,
	EyeClosed,
	EyeOff,
	Feather,
	Flag,
	Flame,
	FlameKindling,
	Flashlight,
	FlaskConical,
	Focus,
	FolderOpen,
	Footprints,
	Gauge,
	Gem,
	Ghost,
	Globe,
	Grab,
	GraduationCap,
	Grid3x3,
	GripVertical,
	Group,
	Hand,
	Haze,
	Heart,
	HeartCrack,
	HeartHandshake,
	Hexagon,
	Hourglass,
	House,
	Import,
	Infinity,
	Info,
	Landmark,
	Languages,
	Lasso,
	Layers,
	LayoutDashboard,
	LayoutGrid,
	Library,
	Link2,
	ListOrdered,
	LoaderCircle,
	LocateOff,
	Lock,
	LockOpen,
	LogIn,
	LogOut,
	Magnet,
	Map,
	MapPin,
	MapPinPlus,
	Maximize,
	Meh,
	Milestone,
	Minus,
	Monitor,
	Moon,
	Mountain,
	MousePointer2,
	Move,
	NotebookPen,
	PaintBucket,
	Palette,
	Pause,
	PawPrint,
	Pencil,
	PencilLine,
	Pentagon,
	PictureInPicture2,
	Pin,
	Play,
	Plug,
	Plus,
	Popcorn,
	Rabbit,
	Redo2,
	RotateCcw,
	Route,
	Ruler,
	Scroll,
	Search,
	Send,
	Settings,
	Shapes,
	Share2,
	Shield,
	ShieldCheck,
	ShieldOff,
	Shrub,
	Shuffle,
	Sigma,
	SkipForward,
	Skull,
	SlidersHorizontal,
	Snail,
	Sparkles,
	Spline,
	Sprout,
	Square,
	Stamp,
	Stars,
	Sun,
	SunDim,
	SunMoon,
	Sunrise,
	Swords,
	Tag,
	Tally3,
	Target,
	Thermometer,
	Timer,
	Tornado,
	Trash2,
	TrendingUp,
	Triangle,
	TriangleAlert,
	Type,
	Undo2,
	UserCircle,
	UserPlus,
	Users,
	UsersRound,
	VenetianMask,
	Volume2,
	VolumeX,
	Wand,
	WandSparkles,
	Waves,
	Waypoints,
	Weight,
	Wind,
	Wrench,
	X,
	Zap,
	ZapOff,
	ZoomIn,
	ZoomOut,
});

/**
 * The Lamplight icon registry — semantic names → Lucide PascalCase glyph names.
 * Lucide (via lucide-react) is the ONLY icon family (clean 2px stroke), and the canonical
 * vocabulary is documented in docs/reference/ICON_VOCABULARY.md;
 * every surface draws through this one registry so there is one
 * family at one weight — no "icon soup". Status keys each map to a DISTINCT shape so
 * meaning survives grayscale (A11Y-011).
 *
 * One concept, one glyph (RC-DSN-3.2): two keys may share a glyph only when one is declared an
 * alias of the other in {@link ICON_ALIASES}. Otherwise a glyph means exactly one thing app-wide.
 *
 * Port note: the design-package Icon read glyph geometry from the global `lucide` UMD
 * (window.lucide). For a self-contained, offline-capable build we resolve the reviewed glyph
 * allowlist through static `lucide-react` imports. Same family, same stroke, much smaller bundle.
 */
export const ICON_REGISTRY = {
	// Global navigation sections
	home: 'House',
	'session-bolt': 'Zap',
	'characters-person': 'Users',
	'atlas-map': 'Map',
	'campaign-scroll': 'Scroll',
	'knowledge-book': 'BookOpen',
	'settings-gear': 'Settings',
	// Status — each a distinct shape (non-color cue)
	success: 'CircleCheck',
	warning: 'TriangleAlert',
	error: 'CircleX',
	info: 'Info',
	// Visibility / actor-safety
	// `dm-only` used to be `Eye` — the SAME glyph as `visibility-players`. VisibilityChip renders
	// icon-only in compact mode, so the app's most safety-critical distinction (can the table see
	// this?) was carried by colour alone at ~33 sites, against the chip's own docstring and A11Y-011.
	// A mask reads as "concealed from the players" and is distinct in grayscale.
	'dm-only': 'VenetianMask',
	hidden: 'EyeOff',
	// `shared` and `mixed` borrowed `characters-person` and `layers`; a chip is read in isolation,
	// so each state now has a shape that belongs to nothing else.
	'visibility-shared': 'Share2',
	'visibility-players': 'Eye',
	'visibility-hidden': 'EyeOff',
	'visibility-mixed': 'Contrast',
	// Common actions / affordances
	close: 'X',
	check: 'Check',
	add: 'Plus',
	remove: 'Minus',
	trash: 'Trash2',
	download: 'Download',
	search: 'Search',
	more: 'Ellipsis',
	'chevron-down': 'ChevronDown',
	'chevron-right': 'ChevronRight',
	'chevron-left': 'ChevronLeft',
	'chevron-up': 'ChevronUp',
	'arrow-right': 'ArrowRight',
	retry: 'RotateCcw',
	loading: 'LoaderCircle',
	move: 'Move',
	pin: 'Pin',
	recent: 'Clock',
	// Display preferences
	motion: 'Wind',
	density: 'Gauge',
	theme: 'SunMoon',
	accessibility: 'Accessibility',
	// Game / live-play extras
	dice: 'Dices',
	heart: 'Heart',
	shield: 'Shield',
	sword: 'Swords',
	audio: 'Volume2',
	'audio-off': 'VolumeX',
	play: 'Play',
	pause: 'Pause',
	skip: 'SkipForward',
	send: 'Send',
	flag: 'Flag',
	sparkle: 'Sparkles',
	scroll: 'Scroll',
	wand: 'Wand',
	book: 'BookOpen',
	map: 'Map',
	link: 'Link2',
	folder: 'FolderOpen',
	controls: 'SlidersHorizontal',
	sliders: 'SlidersHorizontal',
	toolbox: 'BriefcaseBusiness',
	display: 'Monitor',
	eye: 'Eye',
	// Command Center — hub navigation & authoring
	scene: 'LayoutDashboard',
	widget: 'LayoutGrid',
	'new-character': 'UserPlus',
	'new-map': 'MapPinPlus',
	'note-edit': 'NotebookPen',
	note: 'NotebookPen',
	players: 'UsersRound',
	permissions: 'ShieldCheck',
	vault: 'DatabaseZap',
	connection: 'Plug',
	lock: 'Lock',
	unlock: 'LockOpen',
	enter: 'LogIn',

	// ── Maps — view controls (UX-MAP-001/002/003) ─────────────────────────────────────────
	'zoom-in': 'ZoomIn',
	'zoom-out': 'ZoomOut',
	'zoom-fit': 'Maximize',
	globe: 'Globe',
	minimap: 'Map',
	nested: 'PictureInPicture2',
	'new-map-alt': 'MapPinPlus',
	import: 'Import',
	upload: 'CloudUpload',
	undo: 'Undo2',
	redo: 'Redo2',
	preview: 'Eye',
	generate: 'Wand',
	shuffle: 'Shuffle',
	seed: 'Sprout',

	// ── Maps — drawing / fog tool palette (UX-MAP-007) ────────────────────────────────────
	'tool-select': 'MousePointer2',
	'tool-brush': 'Brush',
	'tool-stamp': 'Stamp',
	'tool-shape': 'Shapes',
	'tool-eraser': 'Eraser',
	'tool-text': 'Type',
	'tool-fill': 'PaintBucket',
	'tool-route': 'Route',
	'tool-ruler': 'Ruler',
	'tool-aoe': 'Cone',
	'tool-grid': 'Grid3x3',
	'tool-token': 'Circle',
	'tool-magnet': 'Magnet',
	'tool-crosshair': 'Crosshair',
	// MAP-021 — the expanded tool set (Foundry-style layer-group rail).
	'tool-wall': 'PenTool',
	'tool-room': 'RectangleHorizontal',
	'tool-door': 'DoorOpen',
	'tool-light': 'Lightbulb',
	'tool-scatter': 'SprayCan',
	'tool-measure': 'Ruler',
	'tool-generate': 'Wand',
	'layer-terrain': 'Trees',
	'layer-walls': 'PenTool',
	reveal: 'Sun',
	conceal: 'Cloud',
	feather: 'Feather',

	// ── Maps — layer-type glyphs (UX-MAP-005) ─────────────────────────────────────────────
	'layer-base': 'Mountain',
	'layer-height': 'Spline',
	'layer-political': 'Landmark',
	'layer-climate': 'CloudSun',
	'layer-roads': 'Waypoints',
	'layer-water': 'Waves',
	'layer-wshed': 'Droplets',
	'layer-fog': 'CloudFog',
	'layer-poi': 'MapPin',
	'layer-dm': 'PencilLine',
	'layer-player': 'UsersRound',
	'layer-combat': 'Swords',
	'layer-custom': 'Tag',

	// ── Maps — layer-row & POI affordances (UX-MAP-004/010) ───────────────────────────────
	'drag-handle': 'GripVertical',
	layers: 'Layers',
	opacity: 'Blend',
	duplicate: 'Copy',
	delete: 'Trash2',
	edit: 'Pencil',
	group: 'Group',
	tag: 'Tag',
	poi: 'MapPin',
	waypoint: 'CircleDot',
	distance: 'Ruler',
	travel: 'Footprints',
	validate: 'ClipboardCheck',
	'arrow-left': 'ArrowLeft',
	'arrow-up': 'ArrowUp',

	// ── Conditions (5e) — each a DISTINCT shape so status reads in grayscale (A11Y-011) ─────
	// RC-DSN-3.2 moved six glyphs that another concept already owned: blinded (`hidden`'s EyeOff),
	// invisible (`dm-only`'s mask), paralyzed (the Session nav bolt), petrified (Gem is the d10),
	// restrained (`lock`) and blessed (`sparkle`).
	'cond-blinded': 'EyeClosed',
	'cond-charmed': 'HeartHandshake',
	'cond-deafened': 'EarOff',
	'cond-frightened': 'Ghost',
	'cond-grappled': 'Grab',
	'cond-incapacitated': 'Ban',
	'cond-invisible': 'CircleDashed',
	'cond-paralyzed': 'ZapOff',
	'cond-petrified': 'BrickWall',
	'cond-poisoned': 'FlaskConical',
	'cond-prone': 'ArrowDownToLine',
	'cond-restrained': 'Lasso',
	'cond-stunned': 'Stars',
	'cond-unconscious': 'Moon',
	'cond-exhaustion': 'BatteryLow',
	'cond-concentration': 'Brain',
	'cond-blessed': 'Clover',
	'cond-cursed': 'Skull',
	// ── Conditions (PF2e sample) — `cond-<key>` for every condition `samples/pf2e.json` declares
	// that 5e does not; the shared ones (blinded, frightened, prone…) reuse the 5e key above.
	'cond-clumsy': 'Banana',
	'cond-concealed': 'SunDim',
	'cond-confused': 'Tornado',
	'cond-dazzled': 'Haze',
	'cond-doomed': 'CloudLightning',
	'cond-drained': 'Droplet',
	'cond-dying': 'HeartCrack',
	'cond-enfeebled': 'Dumbbell',
	'cond-fascinated': 'Focus',
	'cond-fatigued': 'BatteryLow',
	'cond-fleeing': 'LogOut',
	'cond-grabbed': 'Grab',
	'cond-hidden': 'Shrub',
	'cond-immobilized': 'Anchor',
	'cond-off-guard': 'ShieldOff',
	'cond-persistent-damage': 'FlameKindling',
	'cond-quickened': 'Rabbit',
	'cond-sickened': 'Thermometer',
	'cond-slowed': 'Snail',
	'cond-stupefied': 'Meh',
	'cond-undetected': 'LocateOff',
	'cond-wounded': 'Bandage',
	// ── Conditions (Generic) — `hidden` is the PF2e key above.
	'cond-afraid': 'Ghost',
	'cond-hindered': 'Weight',
	'cond-inspired': 'Sunrise',
	hourglass: 'Hourglass',
	// Spellcasting
	'spell-slot': 'Diamond',
	'spell-slot-filled': 'Diamond',
	flame: 'Flame',
	ritual: 'Infinity',
	concentration: 'Brain',
	'spell-sparkle': 'WandSparkles',
	'monster-claw': 'PawPrint',
	'theme-color': 'Palette',

	// ── Dice — one face per standard die. Lucide draws no polyhedral dice, so each is the die's
	// outline as it lies on the table: d4 triangle, d8 diamond with its equator, d10 kite (the
	// gem), d12 pentagon, d20 hexagon, d100 the percentile diamond.
	'die-d4': 'Triangle',
	'die-d6': 'Dice6',
	'die-d8': 'DiamondMinus',
	'die-d10': 'Gem',
	'die-d12': 'Pentagon',
	'die-d20': 'Hexagon',
	'die-d100': 'DiamondPercent',

	// ── Board tile families (RC-CAN-2.1 `--color-tile-<family>`) — one identity glyph each. Most
	// are their content's concept (see ICON_ALIASES); encounter, timer and calendar get their own
	// rather than borrowing `sword` and `recent`, so a board can tell them apart at a glance.
	'tile-note': 'NotebookPen',
	'tile-combat': 'Swords',
	'tile-encounter': 'Target',
	'tile-dice': 'Dices',
	'tile-generator': 'Sparkles',
	'tile-handout': 'Scroll',
	'tile-timer': 'Timer',
	'tile-calendar': 'CalendarDays',
	'tile-map': 'Map',
	'tile-character': 'Users',
	'tile-audio': 'Volume2',
	'tile-reference': 'BookOpen',

	// ── System-package concepts (RC-SYS-1.1 schema) — keyed so a caller can build the name from
	// the package value: `sys-resource-${kind}`, `sys-turn-${turnModel.kind}`,
	// `sys-advancement-${model}`, `rest-${recovery}` (`never` has no glyph).
	'sys-package': 'Library',
	'sys-vocabulary': 'Languages',
	'sys-attribute': 'ChartNoAxesColumn',
	'sys-skill': 'GraduationCap',
	'sys-derived': 'Sigma',
	'sys-condition': 'Activity',
	'sys-dice': 'Dices',
	'sys-creature': 'PawPrint',
	'sys-resource-pool': 'Coins',
	'sys-resource-slots': 'Diamond',
	'sys-resource-dice': 'Dices',
	'sys-resource-clock': 'ChartPie',
	'sys-resource-track': 'Columns3',
	'sys-turn-initiative': 'ListOrdered',
	'sys-turn-actions-per-turn': 'Tally3',
	'sys-turn-popcorn': 'Popcorn',
	'sys-turn-none': 'Flashlight',
	'sys-advancement-xp-table': 'TrendingUp',
	'sys-advancement-milestone': 'Milestone',
	'level-up': 'ArrowBigUpDash',
	'rest-short': 'Coffee',
	'rest-long': 'Bed',
	'rest-scene': 'Clapperboard',

	// Transitional direct-Lucide names still used by a few screen data tables. They remain explicit
	// so a typo cannot silently pull Lucide's full runtime registry back into the entry bundle.
	ArrowUp: 'ArrowUp',
	CreditCard: 'CreditCard',
	Hand: 'Hand',
	Minus: 'Minus',
	Monitor: 'Monitor',
	SlidersHorizontal: 'SlidersHorizontal',
	Sprout: 'Sprout',
	UserCircle: 'UserCircle',
	Wrench: 'Wrench',
};

/**
 * Registry keys that name the SAME concept as another key and so draw its glyph: a nav section
 * and its noun, a map layer and what it holds, a tile family and its content, a condition under
 * another system's name. Every key not listed here is its own concept, and no other concept may
 * use its glyph (`Icon.test.ts`). Point an alias at a concept, never at another alias.
 */
export const ICON_ALIASES = Object.freeze({
	'atlas-map': 'map',
	minimap: 'map',
	'campaign-scroll': 'scroll',
	'knowledge-book': 'book',
	'visibility-hidden': 'hidden',
	eye: 'visibility-players',
	// The Player Views tile draws `preview`: what the table sees.
	preview: 'visibility-players',
	trash: 'delete',
	Minus: 'remove',
	sliders: 'controls',
	SlidersHorizontal: 'controls',
	Monitor: 'display',
	ArrowUp: 'arrow-up',
	Sprout: 'seed',
	wand: 'generate',
	'tool-generate': 'generate',
	'new-map-alt': 'new-map',
	note: 'note-edit',
	'tool-measure': 'tool-ruler',
	distance: 'tool-ruler',
	'layer-walls': 'tool-wall',
	'layer-poi': 'poi',
	'layer-player': 'players',
	'layer-combat': 'sword',
	'layer-custom': 'tag',
	'cond-concentration': 'concentration',
	'spell-slot-filled': 'spell-slot',
	// Same condition, another system's word. A package declares at most one of each pair.
	'cond-grabbed': 'cond-grappled',
	'cond-afraid': 'cond-frightened',
	'cond-fatigued': 'cond-exhaustion',
	'tile-note': 'note-edit',
	'tile-combat': 'sword',
	'tile-dice': 'dice',
	'tile-generator': 'sparkle',
	'tile-handout': 'scroll',
	'tile-map': 'map',
	'tile-character': 'characters-person',
	'tile-audio': 'audio',
	'tile-reference': 'book',
	'sys-dice': 'dice',
	'sys-creature': 'monster-claw',
	'sys-resource-slots': 'spell-slot',
	'sys-resource-dice': 'dice',
});

const SIZE_TOKEN = {
	micro: 'var(--icon-size-micro, 16px)',
	sm: 'var(--icon-size-sm, 20px)',
	md: 'var(--icon-size-md, 24px)',
	lg: 'var(--icon-size-lg, 32px)',
	xl: 'var(--icon-size-xl, 48px)',
};

/**
 * Icon — renders a single Lucide glyph at a token size, inheriting currentColor at a 2px stroke.
 *
 * An icon is EITHER meaningful (pass `label` → role=img + aria-label) OR decorative (omit label →
 * aria-hidden, paired with adjacent visible text). Icon-only buttons must always pass a label.
 */
export function Icon({ name, size = 'md', label, color, strokeWidth, style, className, ...rest }) {
	const pascal = ICON_REGISTRY[name] || name;
	const Glyph = GLYPHS[pascal] || Square;
	const px = SIZE_TOKEN[size] || (typeof size === 'number' ? `${size}px` : size);
	const a11y = label ? { role: 'img', 'aria-label': label } : { 'aria-hidden': true };
	return (
		<Glyph
			{...a11y}
			{...rest}
			className={className}
			color={color || 'currentColor'}
			strokeWidth={strokeWidth ?? 2}
			style={{ width: px, height: px, flex: '0 0 auto', display: 'inline-block', ...style }}
		/>
	);
}
