import { ICON_REGISTRY } from './icon-registry';
export { ICON_REGISTRY, ICON_ALIASES } from './icon-registry';

export type IconSize = 'micro' | 'sm' | 'md' | 'lg' | 'xl' | number;

export interface IconProps extends Omit<React.SVGProps<SVGSVGElement>, 'name' | 'color'> {
	/** Semantic registry name (e.g. "session-bolt", "dm-only", "success") or a raw Lucide PascalCase name (e.g. "House"). */
	name: string;
	/** Token size keyword or explicit px. Default "md" (24px). */
	size?: IconSize;
	/** Accessible name. Provide for meaningful icons (role=img); omit for decorative (aria-hidden). Icon-only buttons MUST pass this. */
	label?: string | null;
	/** Override stroke color. Defaults to currentColor. */
	color?: string;
	/** Override stroke width. Defaults to the --icon-stroke-width token (2). */
	strokeWidth?: number;
}

import React from 'react';
import {
	DoorOpen,
	Lightbulb,
	PenTool,
	RectangleHorizontal,
	SprayCan,
	Trees,
	Accessibility,
	Activity,
	Anchor,
	ArrowBigUpDash,
	ArrowDownToLine,
	ArrowLeft,
	ArrowRight,
	ArrowUp,
	Ban,
	Banana,
	Bandage,
	BatteryLow,
	Bed,
	Blend,
	BookOpen,
	Brain,
	BrickWall,
	BriefcaseBusiness,
	Brush,
	CalendarDays,
	ChartNoAxesColumn,
	ChartPie,
	Check,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Circle,
	CircleCheck,
	CircleDashed,
	CircleDot,
	CircleX,
	Clapperboard,
	ClipboardCheck,
	Clock,
	Cloud,
	CloudFog,
	CloudLightning,
	CloudSun,
	CloudUpload,
	Clover,
	Coffee,
	Coins,
	Columns3,
	Cone,
	Contrast,
	Copy,
	CreditCard,
	Crosshair,
	DatabaseZap,
	Diamond,
	DiamondMinus,
	DiamondPercent,
	Dice6,
	Dices,
	Download,
	Droplet,
	Droplets,
	Dumbbell,
	EarOff,
	Ellipsis,
	Eraser,
	Eye,
	EyeClosed,
	EyeOff,
	Feather,
	Flag,
	Flame,
	FlameKindling,
	Flashlight,
	FlaskConical,
	Focus,
	FolderOpen,
	Footprints,
	Gauge,
	Gem,
	Ghost,
	Globe,
	Grab,
	GraduationCap,
	Grid3x3,
	GripVertical,
	Group,
	Hand,
	Haze,
	Heart,
	HeartCrack,
	HeartHandshake,
	Hexagon,
	Hourglass,
	House,
	Import,
	Infinity as InfinityIcon,
	Info,
	Landmark,
	Languages,
	Lasso,
	Layers,
	LayoutDashboard,
	LayoutGrid,
	LayoutList,
	Library,
	Link2,
	ListOrdered,
	LoaderCircle,
	LocateOff,
	Lock,
	LockOpen,
	LogIn,
	LogOut,
	Magnet,
	Map,
	MapPin,
	MapPinPlus,
	Maximize,
	Maximize2,
	Minimize2,
	Meh,
	Milestone,
	Minus,
	Monitor,
	Moon,
	Mountain,
	MousePointer2,
	Move,
	NotebookPen,
	PaintBucket,
	Palette,
	Pause,
	PawPrint,
	Pencil,
	PencilLine,
	Pentagon,
	PictureInPicture2,
	Pin,
	Play,
	Plug,
	Plus,
	Popcorn,
	Rabbit,
	Redo2,
	RotateCcw,
	Route,
	Ruler,
	Scroll,
	Search,
	Send,
	Settings,
	Shapes,
	Share2,
	Shield,
	ShieldCheck,
	ShieldOff,
	Shrub,
	Shuffle,
	Sigma,
	SkipForward,
	Skull,
	SlidersHorizontal,
	Snail,
	Sparkles,
	Spline,
	Sprout,
	Square,
	Stamp,
	Stars,
	Sun,
	SunDim,
	SunMoon,
	Sunrise,
	Swords,
	Tag,
	Tally3,
	Target,
	Thermometer,
	Timer,
	Tornado,
	Trash2,
	TrendingUp,
	Triangle,
	TriangleAlert,
	Type,
	Undo2,
	UserCircle,
	UserPlus,
	Users,
	UsersRound,
	VenetianMask,
	Volume2,
	VolumeX,
	Wand,
	WandSparkles,
	Waves,
	Waypoints,
	Weight,
	Wind,
	Wrench,
	X,
	Zap,
	ZapOff,
	ZoomIn,
	ZoomOut,
} from 'lucide-react';

// Keep the glyph allowlist explicit. Importing Lucide's dynamic `icons` record retained every icon
// in the entry chunk (roughly 0.8 MB before minification), even though the app uses this small,
// release-reviewed vocabulary.
const GLYPHS: Readonly<Record<string, import('lucide-react').LucideIcon>> = Object.freeze({
	DoorOpen,
	Lightbulb,
	PenTool,
	RectangleHorizontal,
	SprayCan,
	Trees,
	Accessibility,
	Activity,
	Anchor,
	ArrowBigUpDash,
	ArrowDownToLine,
	ArrowLeft,
	ArrowRight,
	ArrowUp,
	Ban,
	Banana,
	Bandage,
	BatteryLow,
	Bed,
	Blend,
	BookOpen,
	Brain,
	BrickWall,
	BriefcaseBusiness,
	Brush,
	CalendarDays,
	ChartNoAxesColumn,
	ChartPie,
	Check,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Circle,
	CircleCheck,
	CircleDashed,
	CircleDot,
	CircleX,
	Clapperboard,
	ClipboardCheck,
	Clock,
	Cloud,
	CloudFog,
	CloudLightning,
	CloudSun,
	CloudUpload,
	Clover,
	Coffee,
	Coins,
	Columns3,
	Cone,
	Contrast,
	Copy,
	CreditCard,
	Crosshair,
	DatabaseZap,
	Diamond,
	DiamondMinus,
	DiamondPercent,
	Dice6,
	Dices,
	Download,
	Droplet,
	Droplets,
	Dumbbell,
	EarOff,
	Ellipsis,
	Eraser,
	Eye,
	EyeClosed,
	EyeOff,
	Feather,
	Flag,
	Flame,
	FlameKindling,
	Flashlight,
	FlaskConical,
	Focus,
	FolderOpen,
	Footprints,
	Gauge,
	Gem,
	Ghost,
	Globe,
	Grab,
	GraduationCap,
	Grid3x3,
	GripVertical,
	Group,
	Hand,
	Haze,
	Heart,
	HeartCrack,
	HeartHandshake,
	Hexagon,
	Hourglass,
	House,
	Import,
	Infinity: InfinityIcon,
	Info,
	Landmark,
	Languages,
	Lasso,
	Layers,
	LayoutDashboard,
	LayoutGrid,
	LayoutList,
	Library,
	Link2,
	ListOrdered,
	LoaderCircle,
	LocateOff,
	Lock,
	LockOpen,
	LogIn,
	LogOut,
	Magnet,
	Map,
	MapPin,
	MapPinPlus,
	Maximize,
	Maximize2,
	Minimize2,
	Meh,
	Milestone,
	Minus,
	Monitor,
	Moon,
	Mountain,
	MousePointer2,
	Move,
	NotebookPen,
	PaintBucket,
	Palette,
	Pause,
	PawPrint,
	Pencil,
	PencilLine,
	Pentagon,
	PictureInPicture2,
	Pin,
	Play,
	Plug,
	Plus,
	Popcorn,
	Rabbit,
	Redo2,
	RotateCcw,
	Route,
	Ruler,
	Scroll,
	Search,
	Send,
	Settings,
	Shapes,
	Share2,
	Shield,
	ShieldCheck,
	ShieldOff,
	Shrub,
	Shuffle,
	Sigma,
	SkipForward,
	Skull,
	SlidersHorizontal,
	Snail,
	Sparkles,
	Spline,
	Sprout,
	Square,
	Stamp,
	Stars,
	Sun,
	SunDim,
	SunMoon,
	Sunrise,
	Swords,
	Tag,
	Tally3,
	Target,
	Thermometer,
	Timer,
	Tornado,
	Trash2,
	TrendingUp,
	Triangle,
	TriangleAlert,
	Type,
	Undo2,
	UserCircle,
	UserPlus,
	Users,
	UsersRound,
	VenetianMask,
	Volume2,
	VolumeX,
	Wand,
	WandSparkles,
	Waves,
	Waypoints,
	Weight,
	Wind,
	Wrench,
	X,
	Zap,
	ZapOff,
	ZoomIn,
	ZoomOut,
});

const SIZE_TOKEN: Record<string | number, string> = {
	micro: 'var(--icon-size-micro, 16px)',
	sm: 'var(--icon-size-sm, 20px)',
	md: 'var(--icon-size-md, 24px)',
	lg: 'var(--icon-size-lg, 32px)',
	xl: 'var(--icon-size-xl, 48px)',
};

/**
 * Icon — renders a single Lucide glyph at a token size, inheriting currentColor at a 2px stroke.
 *
 * An icon is EITHER meaningful (pass `label` → role=img + aria-label) OR decorative (omit label →
 * aria-hidden, paired with adjacent visible text). Icon-only buttons must always pass a label.
 */
export function Icon({
	name,
	size = 'md',
	label,
	color,
	strokeWidth,
	style,
	className,
	...rest
}: IconProps) {
	const pascal = ICON_REGISTRY[name] || name;
	const Glyph = GLYPHS[pascal] || Square;
	const px = SIZE_TOKEN[size] || (typeof size === 'number' ? `${size}px` : size);
	const a11y = label ? { role: 'img', 'aria-label': label } : { 'aria-hidden': true };
	return (
		<Glyph
			{...a11y}
			{...rest}
			className={className}
			color={color || 'currentColor'}
			strokeWidth={strokeWidth ?? 2}
			style={{ width: px, height: px, flex: '0 0 auto', display: 'inline-block', ...style }}
		/>
	);
}
