import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { OutputBundle } from 'rollup';
import { defineConfig, loadEnv, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';

const SERVICE_WORKER_SOURCE = fileURLToPath(new URL('./src/sw/service-worker.js', import.meta.url));
const PUBLIC_DIR = fileURLToPath(new URL('./public', import.meta.url));

/** Public-directory files worth holding offline: the boot script, the icons, the manifest. */
function isPrecachablePublicAsset(fileName: string): boolean {
	return /\.(?:js|css|svg|png|webmanifest)$/.test(fileName);
}

/**
 * The EAGER asset set: the entry chunk, everything it imports statically (the vendor and
 * processing-core chunks Vite emits `modulepreload` links for), the stylesheet and the woff2 brand
 * faces. Deliberately NOT every emitted chunk — precaching all ~70 lazy route chunks would pull
 * about 5 MB down on a first visit to buy an offline shell that needs a tenth of it. A route the DM
 * has actually opened is held by the worker's runtime cache instead, so visited routes still work
 * offline. The `.woff` twins of the fonts are left out for the same reason: no browser that can run
 * a service worker asks for them.
 */
function eagerBundleAssets(bundle: OutputBundle): string[] {
	const eager = new Set<string>();
	const visit = (fileName: string) => {
		if (eager.has(fileName)) return;
		const chunk = bundle[fileName];
		if (!chunk || chunk.type !== 'chunk') return;
		eager.add(fileName);
		for (const imported of chunk.imports) visit(imported);
	};
	for (const [fileName, chunk] of Object.entries(bundle)) {
		if (chunk.type === 'chunk' && chunk.isEntry) visit(fileName);
		if (chunk.type === 'asset' && /\.(?:css|woff2)$/.test(fileName)) eager.add(fileName);
	}
	return [...eager];
}

/** Relative paths of every file Vite copies verbatim out of `public/`. */
function publicAssets(): string[] {
	const walk = (dir: string, prefix: string): string[] =>
		readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
			entry.isDirectory()
				? walk(posix.join(dir, entry.name), posix.join(prefix, entry.name))
				: [posix.join(prefix, entry.name)],
		);
	return walk(PUBLIC_DIR, '');
}

/**
 * RC-PLT-2.1 — ships `src/sw/service-worker.js` as the app's service worker.
 *
 * BUILD: the eagerly-loaded assets plus the public shell files become a versioned precache list,
 * prepended to the worker source as `self.__LAMPLIGHT_*`. The version is a hash of the whole
 * bundle, so a build whose output is byte-identical keeps its cache and a build that changed
 * anything gets a new one and evicts the old — the update the toast in
 * `src/platform/serviceWorker.ts` offers.
 *
 * DEV: the same file is served at `/sw.js` with no precache list, which turns it into a pure
 * runtime cache. Vite's dev module URLs are neither hashed nor enumerable ahead of time, so a
 * precache would be a lie; runtime caching is the honest equivalent and is what
 * `tests/e2e/pwa-offline.spec.ts` exercises. The app only registers the worker in dev when the URL
 * carries `?sw=dev`, so a fetch-intercepting worker never appears under the rest of the e2e suite.
 */
function lamplightServiceWorker(): Plugin {
	const readSource = () => readFileSync(SERVICE_WORKER_SOURCE, 'utf8');
	return {
		name: 'lamplight-service-worker',
		configureServer(server) {
			server.middlewares.use((req, res, next) => {
				if ((req.url ?? '').split('?')[0] !== '/sw.js') return next();
				res.setHeader('content-type', 'text/javascript; charset=utf-8');
				res.setHeader('cache-control', 'no-cache');
				res.end(readSource());
			});
		},
		generateBundle(_options, bundle) {
			// `public/` is copied verbatim and never appears in the bundle, so its files — the
			// pre-paint script the shell blocks on, the icons, the manifest — are enumerated here or
			// a cold offline start would have no boot script to run.
			const precache = [
				...eagerBundleAssets(bundle),
				...publicAssets().filter(isPrecachablePublicAsset),
			].sort();
			// Hashed over the WHOLE bundle, not just the precache: a change confined to a lazy route
			// still has to retire the old cache, or the worker would serve that route's stale chunk.
			const version = createHash('sha256')
				.update(Object.keys(bundle).sort().join('\n'))
				.digest('hex')
				.slice(0, 12);
			const header =
				'// Generated by lamplightServiceWorker() in vite.config.ts — do not edit.\n' +
				`self.__LAMPLIGHT_VERSION__ = ${JSON.stringify(version)};\n` +
				`self.__LAMPLIGHT_SHELL__ = 'index.html';\n` +
				`self.__LAMPLIGHT_PRECACHE__ = ${JSON.stringify(['index.html', ...precache], null, '\t')};\n\n`;
			this.emitFile({ type: 'asset', fileName: 'sw.js', source: header + readSource() });
		},
	};
}

function originOf(value: string, protocol: 'https:' | 'wss:'): string | null {
	try {
		const url = new URL(value);
		return url.protocol === protocol ? url.origin : null;
	} catch {
		return null;
	}
}

/** Emit the exact public origins compiled into this build for Electron's main-process allowlist. */
function electronNetworkPolicy(env: Record<string, string>): Plugin {
	const cloudOrigins = new Set<string>();
	for (const [key, protocol] of [
		['VITE_SIGNALING_WS_URL', 'wss:'],
		['VITE_SYNC_API_URL', 'https:'],
		['VITE_APP_API_URL', 'https:'],
	] as const) {
		const origin = originOf(env[key] ?? '', protocol);
		if (origin) cloudOrigins.add(origin);
	}
	const region = env.VITE_CLOUD_REGION?.trim();
	if (region && /^[a-z]{2}(?:-gov)?-[a-z]+-\d$/.test(region)) {
		cloudOrigins.add(`https://cognito-idp.${region}.amazonaws.com`);
	}
	const aiOrigins = new Set<string>();
	for (const value of (env.VITE_AI_ALLOWED_ORIGINS ?? '').split(/\s+/)) {
		const origin = originOf(value, 'https:');
		if (origin) aiOrigins.add(origin);
	}
	return {
		name: 'electron-network-policy',
		apply: 'build',
		generateBundle() {
			this.emitFile({
				type: 'asset',
				fileName: 'electron-network-policy.json',
				source: `${JSON.stringify(
					{
						version: 1,
						cloudOrigins: [...cloudOrigins].sort(),
						aiOrigins: [...aiOrigins].sort(),
					},
					null,
					2,
				)}\n`,
			});
		},
	};
}

/** Stable cache boundaries for startup dependencies shared by every lazy route. */
function appManualChunk(id: string): string | undefined {
	const normalized = id.replaceAll('\\', '/');
	if (normalized.includes('/packages/core/src/')) return 'processing-core';
	if (!normalized.includes('/node_modules/')) return undefined;
	if (
		[
			'/node_modules/react/',
			'/node_modules/react-dom/',
			'/node_modules/react-router/',
			'/node_modules/react-router-dom/',
			'/node_modules/@remix-run/router/',
			'/node_modules/scheduler/',
		].some((part) => normalized.includes(part))
	) {
		return 'vendor-react';
	}
	if (normalized.includes('/node_modules/dexie/')) return 'vendor-storage';
	if (normalized.includes('/node_modules/zod/')) return 'vendor-validation';
	if (
		[
			'/node_modules/amazon-cognito-identity-js/',
			'/node_modules/buffer/',
			'/node_modules/js-cookie/',
			'/node_modules/unfetch/',
		].some((part) => normalized.includes(part))
	) {
		return 'vendor-auth';
	}
	return undefined;
}

// The React GM app. It consumes @dndtools/core directly from its TypeScript source (the core
// package's "exports" points at ./src/index.ts), so Vite/esbuild transforms the framework-agnostic
// Processing Core with no separate build step.
//
// Two build targets, one codebase:
//   • `build`       (default mode) → dist/       — the standard app; first run shows onboarding.
//   • `build:demo`  (--mode demo)  → dist-demo/  — boots straight into the seeded sample campaign.
// The only difference is the `VITE_DEMO_MODE` flag defined below for the `demo` mode, which
// `src/main.tsx` reads to skip the first-run onboarding overlay. Defining it here (rather than in a
// gitignored `.env.demo`) keeps the demo build fully reproducible and committed.
export default defineConfig(({ mode }) => {
	const env = loadEnv(mode, process.cwd(), '');
	return {
		// Relative asset base so the built index.html references `./assets/…` instead of origin-absolute
		// `/assets/…`. This resolves correctly from the Electron app document and a hosted web origin.
		base: './',
		plugins: [react(), electronNetworkPolicy(env), lamplightServiceWorker()],
		define: {
			'import.meta.env.VITE_DEMO_MODE': JSON.stringify(mode === 'demo' ? '1' : ''),
			// `amazon-cognito-identity-js` pulls in `buffer@4.x`, whose module init reads a bare
			// `global` — undefined in the browser, so the whole app (AuthProvider wraps the root)
			// throws `global is not defined` and never mounts. Map it to `globalThis` at build time
			// (compile-time, so it also works under the strict prod/Electron CSP — no inline shim).
			global: 'globalThis',
		},
		build: {
			// The offline processing core and on-demand monster catalog are intentionally dense but
			// compress well. Keep warning headroom tight enough to catch a new monolithic route.
			chunkSizeWarningLimit: 650,
			rollupOptions: { output: { manualChunks: appManualChunk } },
		},
		server: { port: 5273, strictPort: false },
		preview: { port: 4273, strictPort: false },
	};
});
